Exclude unused component metrics
cnescatlab/sonar-cnes-report pull request #179
Opened 2020-11-23 17:19 UTC by jeritiana

# Fixed issues
* Fix #86

# Proposed changes
* Always exclude component `Name` and `Path` from metrics (do not rely on the value)

2020-11-24 13:36 UTC, Sancretor requested changes

2020-11-24 13:36 UTC, Sancretor commented on src/main/java/fr/cnes/sonar/report/providers/ComponentProvider.java
> +            return false;
Could you please refactor your code so that this method only has one return statement ?

2020-11-30 10:56 UTC, Sancretor commented
As we need this fix to release the next version of the plugin, we merge this PR inside a dev branch to do the requested changes ourselves.
Thank you so much for your contribution !

2020-11-30 10:57 UTC, merged

2020-12-09 11:55 UTC, jeritiana commented
Ho, I just saw your comment. I just pushed the observations I made but yes, feel free to adapt it to your liking!